CLASS LHC_ZKJKR_LIB_BOOK_TAB_1656 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZkjkrLibBookTab1656
        RESULT result.
ENDCLASS.

CLASS LHC_ZKJKR_LIB_BOOK_TAB_1656 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
